name: Baseline

on:
  push:
    branches: [main]

permissions:
  contents: read

env:
  URNERYS: app.urnerys.dev
  BUILD: "github-run-${{ github.run_id }}-${{ github.run_attempt }}"
  BISCUIT_PRIVATE_KEY: ed25519-private/869fb6eef6b04ee212479b344690549c9e77bde6c3412b5badcd8b65f89d8c70

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: |
          curl -sf -X POST -H "Content-Type: application/json" -d '{ "id": "'"$BUILD"'", "build": { "origin": { "commit": "${{ github.sha }}" } } }' "https://$URNERYS/api/v1/projects/webshot/builds"

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - run: nix run .#nix-develop .#workflow

      - run: cargo test --locked --all-features --all-targets

      - run: |
          curl -sf -X PATCH -H "Content-Type: application/json" -d '{ "baseline": { "build": "'"$BUILD"'" } }' "https://$URNERYS/api/v1/projects/webshot/baselines/production"
